### ISSUE TITLE
Multi-column association / condition

### ISSUE THREAD

**Issue by dcolley** [balderdashy/waterline-docs#28]
I'm porting our api from yii to sails.js. In the Yii model for "Project" I have a 'relation' to "Comment" as follows:
```php
	public function relations() {
		return array(
			'comments' => array( self::HAS_MANY, 'Comment', 'obj_id', 'condition'=>'obj = "Project" AND comments.status='.Comment::STATUS_APPROVED, 'order'=>'comments.create_time DESC'),
			'commentCount' => array(self::STAT, 'Comment', 'obj_id', 'condition'=>'obj = "Project" AND status='.Comment::STATUS_APPROVED),
		);
	}
```
How can I model this in sails.js?

I have created a model attribute function

```javascript
	comments: function( cb ) {
		Comment.find({ obj: "Project", obj_id: this.id }).exec( function(err, list) {
			cb( err, list );
		});
	}
```
... but it should be possible via associations... :/
Is there any documentation on this?

**Comment by devinivy** [comment]
Currently there's no way to create this sort of association using waterline.  If you think this is a missing feature, feel free to raise a feature request over on the [waterline repo](https://github.com/balderdashy/waterline/issues).  For the time being, I would suggest adding a custom model method (http://sailsjs.org/#!/documentation/concepts/ORM/Models.html?q=model-methods-%28aka-static-or-class-methods%29) rather than an attribute.
