### ISSUE TITLE
databases in mongodb and mysql are not working properly together

### ISSUE THREAD

**Issue by akshitjain** [balderdashy/waterline-docs#73]
If there are two databases one in mongodb and other in mysql and now we want to associate the two databases together then the queries doesn't give the expected output as it gives on databases in pure mysql or mongodb.
eg.User.find()
.populate('pets')
.exec(function(err, users) {});
on applying this function where user is in mongodb while pets is in mysql then the function doesn't club the pets according to users id's .Please look into this

**Comment by dmarcelino** [comment]
Hi @akshitjain, this is not the right project to submit a waterline issue, this project is only for documentation. Furthermore, your issue is a know one, check balderdashy/waterline#925, namely https://github.com/balderdashy/waterline/issues/925#issuecomment-89614487. I suggest you subscribe to that issue.

I'm closing this for now, please re-open if you feel this wasn't fully answered.
